// Re-export of tree-sitter-rust with a permissive tree-sitter peer range.
// Generated by scripts/scaffold-grammar-wrappers.mjs — do not edit by hand.
"use strict";
module.exports = require("upstream-grammar");
