export type RepoId = string;
export type SymbolId = string;
export type VersionId = string;

export type EdgeType = "import" | "call" | "config";
export type EdgeResolutionStrategy = "exact" | "heuristic" | "unresolved";
export type SymbolKind =
  | "function"
  | "class"
  | "interface"
  | "type"
  | "module"
  | "method"
  | "constructor"
  | "variable";

export type Visibility =
  | "public"
  | "protected"
  | "private"
  | "exported"
  | "internal";

export interface RepoRow {
  repo_id: RepoId;
  root_path: string;
  config_json: string;
  created_at: string;
}

export interface FileRow {
  file_id: number;
  repo_id: RepoId;
  rel_path: string;
  content_hash: string;
  language: string;
  byte_size: number;
  last_indexed_at: string | null;
  directory: string;
}

export interface SymbolRow {
  symbol_id: SymbolId;
  repo_id: RepoId;
  file_id: number;
  kind: SymbolKind;
  name: string;
  exported: 0 | 1;
  visibility: Visibility | null;
  language: string;

  range_start_line: number;
  range_start_col: number;
  range_end_line: number;
  range_end_col: number;

  ast_fingerprint: string;
  signature_json: string | null;
  summary: string | null;
  invariants_json: string | null;
  side_effects_json: string | null;

  updated_at: string;
}

export interface EdgeRow {
  /** Auto-generated by SQLite AUTOINCREMENT - only present when reading from DB */
  edge_id?: number;
  repo_id: RepoId;
  from_symbol_id: SymbolId;
  to_symbol_id: SymbolId;
  type: EdgeType;
  weight: number;
  provenance: string | null;
  created_at: string;
  /**
   * Confidence score for edge resolution (0.0-1.0).
   * - 1.0: TS Compiler API resolved
   * - 0.9: Import-trace resolved
   * - 0.8: Same-file symbol match
   * - 0.6: Class method heuristic
   * - 0.3: Unresolved
   * @default 1.0
   */
  confidence?: number;
  /**
   * Resolution strategy used for call-edge target inference.
   * - exact: direct/static target resolution
   * - heuristic: inferred target using heuristics
   * - unresolved: unresolved placeholder target
   */
  resolution_strategy?: EdgeResolutionStrategy;
}

export interface SymbolEmbeddingRow {
  symbol_id: SymbolId;
  model: string;
  embedding_vector: Buffer;
  version: string;
  card_hash: string;
  created_at: string;
  updated_at: string;
}

export interface VersionRow {
  version_id: VersionId;
  repo_id: RepoId;
  created_at: string;
  reason: string | null;
  prev_version_hash: string | null;
  version_hash: string | null;
}

export interface SymbolVersionRow {
  version_id: VersionId;
  symbol_id: SymbolId;
  ast_fingerprint: string;
  signature_json: string | null;
  summary: string | null;
  invariants_json: string | null;
  side_effects_json: string | null;
}

export interface MetricsRow {
  symbol_id: SymbolId;
  fan_in: number;
  fan_out: number;
  churn_30d: number;
  test_refs_json: string | null;
  updated_at: string;
}

export interface AuditRow {
  event_id: number;
  timestamp: string;
  tool: string;
  decision: string;
  repo_id: string | null;
  symbol_id: string | null;
  details_json: string;
}

export interface SliceHandleRow {
  handle: string;
  repo_id: RepoId;
  created_at: string;
  expires_at: string;
  min_version: VersionId | null;
  max_version: VersionId | null;
  slice_hash: string;
  spillover_ref: string | null;
}

export interface CardHashRow {
  card_hash: string;
  card_blob: string;
  created_at: string;
}

export interface ToolPolicyHashRow {
  policy_hash: string;
  policy_blob: string;
  created_at: string;
}

export interface TsconfigHashRow {
  tsconfig_hash: string;
  tsconfig_blob: string;
  created_at: string;
}

export interface SymbolReferenceRow {
  ref_id: number;
  repo_id: string;
  symbol_name: string;
  file_id: number;
  line_number: number | null;
  created_at: string;
}

export interface SyncArtifactRow {
  artifact_id: string;
  repo_id: RepoId;
  version_id: VersionId;
  commit_sha: string | null;
  branch: string | null;
  artifact_hash: string;
  compressed_data: string;
  created_at: string;
  size_bytes: number;
}
