// Re-export of tree-sitter-kotlin with a permissive tree-sitter peer range.
// Generated by scripts/scaffold-grammar-wrappers.mjs — do not edit by hand.
"use strict";

const { dirname } = require("node:path");
const { createRequire } = require("node:module");

const upstreamManifest = require.resolve("upstream-grammar/package.json");
const upstreamRequire = createRequire(upstreamManifest);
module.exports = upstreamRequire("node-gyp-build")(dirname(upstreamManifest));
