// Built-in JS/TS method names that can never resolve to repo symbols.
// Filtering these from unresolved edges reduces totalCallEdges denominator.
//
// IMPORTANT: Only include names that are structurally unambiguous — names that
// are extremely unlikely to be user-defined functions. Short, generic names like
// "run", "find", "get", "send" should NOT be here because isBuiltinCall() is
// context-free and cannot distinguish e.g. Array.find() from userService.find().
const BUILTIN_IDENTIFIERS = new Set([
  // Array prototype
  "push",
  "pop",
  "shift",
  "unshift",
  "splice",
  "slice",
  "concat",
  "map",
  "filter",
  "reduce",
  "reduceRight",
  "findIndex",
  "some",
  "every",
  "includes",
  "indexOf",
  "lastIndexOf",
  "sort",
  "reverse",
  "flat",
  "flatMap",
  "fill",
  "copyWithin",
  "forEach",
  "entries",
  "keys",
  "values",
  "join",
  "at",
  // String prototype
  "split",
  "trim",
  "trimStart",
  "trimEnd",
  "replace",
  "replaceAll",
  "startsWith",
  "endsWith",
  "toLowerCase",
  "toUpperCase",
  "toLocaleLowerCase",
  "toLocaleUpperCase",
  "match",
  "matchAll",
  "search",
  "padStart",
  "padEnd",
  "charAt",
  "charCodeAt",
  "codePointAt",
  "repeat",
  "substring",
  "localeCompare",
  // Object static
  "assign",
  "freeze",
  "defineProperty",
  "getOwnPropertyNames",
  "getPrototypeOf",
  "create",
  "fromEntries",
  // Math static
  "floor",
  "ceil",
  "round",
  "max",
  "min",
  "abs",
  "sqrt",
  "pow",
  "random",
  "log",
  // JSON
  "stringify",
  "parse",
  // Number/Date
  "toFixed",
  "toPrecision",
  "toISOString",
  "getTime",
  "toLocaleString",
  "parseInt",
  "parseFloat",
  "isNaN",
  "isFinite",
  "isInteger",
  // Promise
  "then",
  "catch",
  "finally",
  // Map/Set/WeakMap/WeakSet instance
  "has",
  "get",
  "set",
  "delete",
  "clear",
  "add",
  // Console
  "warn",
  "error",
  "info",
  "debug",
  "trace",
  // RegExp
  "test",
  "exec",
  // Node.js fs/path/url/events
  "readFileSync",
  "writeFileSync",
  "existsSync",
  "mkdirSync",
  "readFile",
  "writeFile",
  "readdir",
  "readdirSync",
  "stat",
  "statSync",
  "rmSync",
  "unlinkSync",
  "copyFileSync",
  "renameSync",
  "chmodSync",
  "createReadStream",
  "createWriteStream",
  "dirname",
  "basename",
  "extname",
  "relative",
  "isAbsolute",
  "fileURLToPath",
  "pathToFileURL",
  "once",
  "emit",
  "removeListener",
  "removeAllListeners",
  // Node.js os/crypto/util
  "tmpdir",
  "cpus",
  "homedir",
  "platform",
  "arch",
  "release",
  "totalmem",
  "freemem",
  "createHash",
  "randomBytes",
  "randomUUID",
  "scryptSync",
  "pbkdf2Sync",
  "promisify",
  "deprecate",
  "callbackify",
  // process
  "exit",
  "cwd",
  "env",
  // Database
  "prepare",
  "transaction",
  // Zod schema builder methods
  "object",
  "string",
  "number",
  "boolean",
  "array",
  "enum",
  "optional",
  "nullable",
  "default",
  "describe",
  "int",
  "transform",
  "refine",
  "union",
  "intersection",
  "literal",
  "tuple",
  "record",
  "lazy",
  "coerce",
  "safeParse",
  "parseAsync",
  "passthrough",
  "strict",
  "extend",
  "merge",
  "pick",
  "omit",
  "partial",
  "required",
  "shape",
  "min",
  "max",
  "length",
  "email",
  "url",
  "uuid",
  "regex",
  // tree-sitter AST node methods
  "childForFieldName",
  "children",
  "namedChildren",
  "childCount",
  "namedChild",
  "child",
  "firstChild",
  "lastChild",
  "nextSibling",
  "previousSibling",
  "parent",
  "descendantsOfType",
  "walk",
  "startPosition",
  "endPosition",
  // Rust standard library (unambiguous names only)
  "to_string",
  "unwrap",
  "unwrap_or",
  "unwrap_or_else",
  "expect",
  "is_some",
  "is_none",
  "is_ok",
  "is_err",
  "as_ref",
  "as_mut",
  "as_str",
  "as_bytes",
  "collect",
  "iter",
  "into_iter",
  "len",
  "is_empty",
  "contains",
  "clone",
  "to_owned",
  "fmt",
  "display",
  "write_str",
  "write_fmt",
  // Rust standard library (extended — unambiguous iterator/collection methods)
  "entry",
  "or_insert",
  "or_default",
  "and_then",
  "flat_map",
  "skip",
  "enumerate",
  "zip",
  "position",
  "sum",
  "sort_by",
  "sort_by_key",
  "dedup",
  "retain",
  "truncate",
  "drain",
  "append",
  "with_capacity",
  "capacity",
  "reserve",
  "shrink_to_fit",
  "as_slice",
  "to_vec",
  "to_string_lossy",
  "chars",
  "bytes",
  "lines",
  "starts_with",
  "ends_with",
  "contains_key",
  "get_or_insert",
  "read_to_string",
  "write_all",
  "sleep",
  "yield_now",
  // Testing frameworks
  "it",
  "beforeEach",
  "afterEach",
  "beforeAll",
  "afterAll",
  // Testing assertions/matchers (Jest/Vitest/Playwright/Testing Library)
  "locator",
  "click",
  "fill",
  "press",
  "check",
  "uncheck",
  "selectOption",
  "waitFor",
  "waitForSelector",
  "waitForNavigation",
  "waitForTimeout",
  "toBeVisible",
  "toHaveText",
  "toContain",
  "toBe",
  "toEqual",
  "toThrow",
  "toMatchSnapshot",
  "toMatchInlineSnapshot",
  "toHaveBeenCalled",
  "toHaveBeenCalledWith",
  "toHaveLength",
  "toBeTruthy",
  "toBeFalsy",
  "toBeNull",
  "toBeUndefined",
  "toBeDefined",
  "toBeGreaterThan",
  "toBeLessThan",
  "getByRole",
  "getByText",
  "getByTestId",
  "findByText",
  "queryByText",
  "getByLabelText",
  "getByPlaceholderText",
  // Global functions
  "encodeURIComponent",
  "decodeURIComponent",
  "encodeURI",
  "decodeURI",
  "setTimeout",
  "clearTimeout",
  "setInterval",
  "clearInterval",
  "requestAnimationFrame",
  "cancelAnimationFrame",
  "atob",
  "btoa",
  "fetch",
  // Misc (unambiguous only)
  "toString",
  "valueOf",
  "toJSON",
  "iterator",
  "isArray",
]);

// Common Rust macros that should be filtered as non-resolvable.
// These retain the ! suffix for matching against raw callee identifiers.
const BUILTIN_MACROS = new Set([
  "assert!",
  "assert_eq!",
  "assert_ne!",
  "debug_assert!",
  "debug_assert_eq!",
  "debug_assert_ne!",
  "println!",
  "print!",
  "eprintln!",
  "eprint!",
  "format!",
  "write!",
  "writeln!",
  "vec!",
  "todo!",
  "unimplemented!",
  "unreachable!",
  "panic!",
  "cfg!",
  "env!",
  "include!",
  "include_str!",
  "include_bytes!",
  "log!",
  "info!",
  "warn!",
  "error!",
  "debug!",
  "trace!",
  "matches!",
  "dbg!",
  "concat!",
  "stringify!",
  "compile_error!",
  "file!",
  "line!",
  "column!",
  "module_path!",
  "option_env!",
  "cfg_if!",
]);

// Built-in constructors that will never resolve to repo symbols
const BUILTIN_CONSTRUCTORS = new Set([
  "Map",
  "Set",
  "WeakMap",
  "WeakSet",
  "Error",
  "TypeError",
  "RangeError",
  "SyntaxError",
  "ReferenceError",
  "Date",
  "RegExp",
  "Promise",
  "Array",
  "Object",
  "Number",
  "String",
  "Boolean",
  "Symbol",
  "Int8Array",
  "Uint8Array",
  "Float32Array",
  "Float64Array",
  "ArrayBuffer",
  "SharedArrayBuffer",
  "DataView",
  "Proxy",
  "Reflect",
  "URL",
  "URLSearchParams",
  "AbortController",
  "AbortSignal",
  "TextEncoder",
  "TextDecoder",
  "ReadableStream",
  "WritableStream",
  "Buffer",
  "EventEmitter",
  "Headers",
  "Request",
  "Response",
  "FormData",
  // Rust standard types (extracted as constructors)
  "Vec",
  "HashMap",
  "HashSet",
  "BTreeMap",
  "BTreeSet",
  "Some",
  "None",
  "Ok",
  "Err",
  "Box",
  "Rc",
  "Arc",
  "Cell",
  "RefCell",
  "Mutex",
  "RwLock",
  "PathBuf",
  "OsString",
  "CString",
]);

// JS/TS built-in global namespace objects.
// When used as a prefix in dotted calls (e.g. Math.floor, JSON.stringify),
// the call should not resolve to a repo symbol.
const BUILTIN_GLOBAL_NAMESPACES = new Set([
  "Date",
  "Math",
  "JSON",
  "Object",
  "Array",
  "String",
  "Number",
  "Boolean",
  "RegExp",
  "Promise",
  "Symbol",
  "Proxy",
  "Reflect",
  "console",
  "process",
  "globalThis",
  "window",
  "document",
  "Intl",
  "Atomics",
  "SharedArrayBuffer",
  "WeakRef",
  "FinalizationRegistry",
]);

// Node.js built-in module names used as namespace imports.
// When used as a prefix in dotted calls (e.g. fs.readFile, path.join),
// the call should not resolve to a repo symbol.
const NODE_BUILTIN_MODULE_NAMES = new Set([
  "path",
  "fs",
  "os",
  "url",
  "util",
  "crypto",
  "http",
  "https",
  "net",
  "dns",
  "tls",
  "child_process",
  "cluster",
  "stream",
  "zlib",
  "buffer",
  "events",
  "querystring",
  "readline",
  "assert",
  "perf_hooks",
  "worker_threads",
  "v8",
  "vm",
  "inspector",
]);

/** Check if an unresolved call target is a built-in that should be skipped. */
function isBuiltinCall(targetName: string): boolean {
  if (
    BUILTIN_IDENTIFIERS.has(targetName) ||
    BUILTIN_CONSTRUCTORS.has(targetName)
  ) {
    return true;
  }
  if (BUILTIN_MACROS.has(targetName)) {
    return true;
  }
  // Handle compound names like "Vec::new", "HashMap::new", "Some(x)"
  if (targetName.includes(":")) {
    const parts = targetName.split(":");
    if (
      parts.some(
        (p) =>
          BUILTIN_CONSTRUCTORS.has(p) ||
          BUILTIN_IDENTIFIERS.has(p) ||
          BUILTIN_MACROS.has(p),
      )
    ) {
      return true;
    }
  }
  return false;
}

export {
  BUILTIN_CONSTRUCTORS,
  BUILTIN_GLOBAL_NAMESPACES,
  BUILTIN_IDENTIFIERS,
  BUILTIN_MACROS,
  NODE_BUILTIN_MODULE_NAMES,
  isBuiltinCall,
};
