/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NativeClusterSymbol {
  symbolId: string
}
export interface NativeClusterEdge {
  fromSymbolId: string
  toSymbolId: string
}
export interface NativeClusterAssignment {
  symbolId: string
  clusterId: string
  membershipScore: number
}
export interface NativeProcessSymbol {
  symbolId: string
  name: string
}
export interface NativeProcessCallEdge {
  callerId: string
  calleeId: string
}
export interface NativeProcessStep {
  symbolId: string
  stepOrder: number
}
export interface NativeProcess {
  processId: string
  entrySymbolId: string
  steps: Array<NativeProcessStep>
  depth: number
}
/** Input file descriptor passed from TypeScript to Rust. */
export interface NativeFileInput {
  /** Relative path from repo root (forward slashes). */
  relPath: string
  /** Absolute path on disk. */
  absolutePath: string
  /** Repository identifier. */
  repoId: string
  /** Language identifier (e.g., "ts", "tsx", "js", "py", "go"). */
  language: string
}
/** Range within a source file (1-indexed lines, 0-indexed columns). */
export interface NativeRange {
  startLine: number
  startCol: number
  endLine: number
  endCol: number
}
/** Extracted symbol from AST analysis. */
export interface NativeParsedSymbol {
  /** Stable symbol ID: sha256("{repoId}:{relPath}:{kind}:{name}:{astFingerprint}"). */
  symbolId: string
  /** AST fingerprint hash. */
  astFingerprint: string
  /**
   * Symbol kind: "function", "class", "interface", "type_alias", "method",
   * "constructor", "variable", "module", "enum", "property".
   */
  kind: string
  /** Symbol name. */
  name: string
  /** Whether the symbol is exported. */
  exported: boolean
  /** Visibility: "public", "private", "protected", "internal", or empty. */
  visibility: string
  /** Source range. */
  range: NativeRange
  /** JSON-encoded signature object. */
  signatureJson: string
  /** One-line summary from JSDoc or auto-generated. */
  summary: string
  /** JSON-encoded invariants array. */
  invariantsJson: string
  /** JSON-encoded side-effects array. */
  sideEffectsJson: string
}
/** Extracted import statement. */
export interface NativeParsedImport {
  /** Module specifier (e.g., "./utils.js", "lodash"). */
  specifier: string
  /** Whether the import is relative (starts with . or ..). */
  isRelative: boolean
  /** Whether the import is from an external package. */
  isExternal: boolean
  /** Named imports (e.g., ["foo", "bar"]). */
  namedImports: Array<string>
  /** Default import name, if any. */
  defaultImport?: string
  /** Namespace import name (e.g., "* as ns"), if any. */
  namespaceImport?: string
  /** Source range. */
  range: NativeRange
}
/** Extracted call site. */
export interface NativeParsedCall {
  /** Node ID of the caller (enclosing symbol). */
  callerName: string
  /** Callee identifier (e.g., "foo", "this.bar", "ns.baz"). */
  calleeIdentifier: string
  /**
   * Call type: "direct", "method", "constructor", "super", "tagged_template",
   * "optional_chain", "computed".
   */
  callType: string
  /** Source range. */
  range: NativeRange
}
/** Complete parse result for a single file. */
export interface NativeParsedFile {
  /** Relative path (matches input). */
  relPath: string
  /** SHA-256 hex digest of file content. */
  contentHash: string
  /** Extracted symbols. */
  symbols: Array<NativeParsedSymbol>
  /** Extracted imports. */
  imports: Array<NativeParsedImport>
  /** Extracted calls. */
  calls: Array<NativeParsedCall>
  /** Parse error message, if any. */
  parseError?: string
}
export declare function parseFiles(files: Array<NativeFileInput>, threadCount: number): Array<NativeParsedFile>
export declare function hashContentNative(content: string): string
export declare function generateSymbolIdNative(repoId: string, relPath: string, kind: string, name: string, fingerprint: string): string
export declare function computeClusters(symbols: Array<NativeClusterSymbol>, edges: Array<NativeClusterEdge>, minClusterSize: number): Array<NativeClusterAssignment>
export declare function traceProcesses(symbols: Array<NativeProcessSymbol>, callEdges: Array<NativeProcessCallEdge>, maxDepth: number, entryPatterns: Array<string>): Array<NativeProcess>
