/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NativeClusterSymbol {
  symbolId: string
}
export interface NativeClusterEdge {
  fromSymbolId: string
  toSymbolId: string
}
export interface NativeClusterAssignment {
  symbolId: string
  clusterId: string
  membershipScore: number
}
export interface NativeProcessSymbol {
  symbolId: string
  name: string
}
export interface NativeProcessCallEdge {
  callerId: string
  calleeId: string
}
export interface NativeProcessStep {
  symbolId: string
  stepOrder: number
}
export interface NativeProcess {
  processId: string
  entrySymbolId: string
  steps: Array<NativeProcessStep>
  depth: number
}
export interface NapiScipMetadata {
  version: number
  toolName: string
  toolVersion: string
  toolArguments: Array<string>
  projectRoot: string
  textDocumentEncoding: string
}
export interface NapiScipRange {
  startLine: number
  startCol: number
  endLine: number
  endCol: number
}
export interface NapiScipRelationship {
  symbol: string
  isReference: boolean
  isImplementation: boolean
  isTypeDefinition: boolean
  isDefinition: boolean
}
export interface NapiScipDiagnostic {
  severity: number
  code: string
  message: string
  source: string
  range?: NapiScipRange
}
export interface NapiScipOccurrence {
  range: NapiScipRange
  symbol: string
  symbolRoles: number
  overrideDocumentation: Array<string>
  syntaxKind: number
  diagnostics: Array<NapiScipDiagnostic>
}
export interface NapiScipSymbolInfo {
  symbol: string
  documentation: Array<string>
  relationships: Array<NapiScipRelationship>
  kind: number
  displayName: string
  signatureDocumentation?: string
  enclosingSymbol?: string
}
export interface NapiScipDocument {
  language: string
  relativePath: string
  occurrences: Array<NapiScipOccurrence>
  symbols: Array<NapiScipSymbolInfo>
}
export interface NapiScipExternalSymbol {
  symbol: string
  documentation: Array<string>
  relationships: Array<NapiScipRelationship>
  kind: number
  displayName: string
  signatureDocumentation?: string
}
/** Input file descriptor passed from TypeScript to Rust. */
export interface NativeFileInput {
  /** Relative path from repo root (forward slashes). */
  relPath: string
  /** Absolute path on disk. */
  absolutePath: string
  /** Repository identifier. */
  repoId: string
  /** Language identifier (e.g., "ts", "tsx", "js", "py", "go"). */
  language: string
}
/** Range within a source file (1-indexed lines, 0-indexed columns). */
export interface NativeRange {
  startLine: number
  startCol: number
  endLine: number
  endCol: number
}
/**
 * A single parameter in a function/method signature.
 *
 * Typed fields replace the previous JSON-encoded `signature_json: String` so
 * that callers receive structured data rather than opaque text that must be
 * re-parsed on the TypeScript side.
 */
export interface NativeSymbolSignatureParam {
  /** Parameter name as it appears in source. */
  name: string
  /** Declared type annotation, if present (e.g. `"string"`, `"Request | null"`). */
  typeName?: string
}
/**
 * Structured representation of a function or method signature.
 *
 * `None` fields are omitted rather than serialised as empty arrays/strings,
 * keeping the napi payload compact. The struct is `None` on the parent symbol
 * when there are no params, no return type, and no generics (e.g. plain
 * variables or class declarations).
 */
export interface NativeSymbolSignature {
  /** Parameter list. `None` when the symbol has no parameters. */
  params?: Array<NativeSymbolSignatureParam>
  /** Return type annotation, if present (e.g. `"Promise<User>"`). */
  returns?: string
  /** Generic type parameters (e.g. `["T", "U extends Serializable"]`). */
  generics?: Array<string>
}
/** Extracted symbol from AST analysis. */
export interface NativeParsedSymbol {
  /**
   * Stable per-file nodeId, format `${name}:${startLine}:${startCol}`.
   * Distinct from `symbol_id` (a cross-repo SHA-256) — `node_id` is the
   * key used by same-file edge resolution and call-site joining in
   * `buildSymbolIndexMaps`. Must match the `caller_node_id` emitted by
   * `NativeParsedCall` for the enclosing symbol.
   */
  nodeId: string
  /** Stable symbol ID: sha256("{repoId}:{relPath}:{kind}:{name}:{astFingerprint}"). */
  symbolId: string
  /** AST fingerprint hash. */
  astFingerprint: string
  /**
   * Symbol kind: "function", "class", "interface", "type_alias", "method",
   * "constructor", "variable", "module", "enum", "property".
   */
  kind: string
  /** Symbol name. */
  name: string
  /** Whether the symbol is exported. */
  exported: boolean
  /** Visibility: "public", "private", "protected", "internal", or empty. */
  visibility: string
  /** Source range. */
  range: NativeRange
  /** Parsed signature object. */
  signature?: NativeSymbolSignature
  /** One-line summary from JSDoc or auto-generated. */
  summary: string
  /** Invariants array. */
  invariants: Array<string>
  /** Side-effects array. */
  sideEffects: Array<string>
  /** Role tags inferred from name/path heuristics. */
  roleTags: Array<string>
  /**
   * Raw decorator / annotation / attribute source text attached to this
   * symbol. Includes the leading sigil (e.g. `@Component(...)`, `@override`,
   * `#[derive(Debug)]`). Empty for languages without a decorator concept.
   */
  decorators: Array<string>
  /** Search-oriented text including identifier splits, summary, tags, and path hints. */
  searchText: string
  /** Summary quality score: 1.0 = doc comment, 0.4 = typed function, 0.3 = heuristic, 0.0 = none. */
  summaryQuality?: number
}
/** Extracted import statement. */
export interface NativeParsedImport {
  /** Module specifier (e.g., "./utils.js", "lodash"). */
  specifier: string
  /** Whether the import is relative (starts with . or ..). */
  isRelative: boolean
  /** Whether the import is from an external package. */
  isExternal: boolean
  /** Named imports (e.g., ["foo", "bar"]). */
  namedImports: Array<string>
  /** Default import name, if any. */
  defaultImport?: string
  /** Namespace import name (e.g., "* as ns"), if any. */
  namespaceImport?: string
  /**
   * Whether this statement re-exports (e.g., `export … from`, `pub use`).
   * Languages without a re-export concept (Java, C#) always set this to false.
   */
  isReExport: boolean
  /** Source range. */
  range: NativeRange
}
/** Extracted call site. */
export interface NativeParsedCall {
  /**
   * Stable nodeId of the caller (enclosing symbol), format
   * `${name}:${startLine}:${startCol}`. Must match the `node_id` of a
   * `NativeParsedSymbol` emitted for the same file so downstream
   * `buildSymbolIndexMaps` can join call sites to their callers.
   */
  callerNodeId: string
  /** Callee identifier (e.g., "foo", "this.bar", "ns.baz"). */
  calleeIdentifier: string
  /**
   * Call type: "direct", "method", "constructor", "super", "tagged_template",
   * "optional_chain", "computed".
   */
  callType: string
  /** Source range. */
  range: NativeRange
}
/** Complete parse result for a single file. */
export interface NativeParsedFile {
  /** Relative path (matches input). */
  relPath: string
  /** SHA-256 hex digest of file content. */
  contentHash: string
  /** Extracted symbols. */
  symbols: Array<NativeParsedSymbol>
  /** Extracted imports. */
  imports: Array<NativeParsedImport>
  /** Extracted calls. */
  calls: Array<NativeParsedCall>
  /** Parse error message, if any. */
  parseError?: string
}
export declare function parseFiles(files: Array<NativeFileInput>, threadCount: number): Array<NativeParsedFile>
export declare function hashContentNative(content: string): string
export declare function generateSymbolIdNative(repoId: string, relPath: string, kind: string, name: string, fingerprint: string): string
export declare function computeClusters(symbols: Array<NativeClusterSymbol>, edges: Array<NativeClusterEdge>, minClusterSize: number): Array<NativeClusterAssignment>
export declare function traceProcesses(symbols: Array<NativeProcessSymbol>, callEdges: Array<NativeProcessCallEdge>, maxDepth: number, entryPatterns: Array<string>): Array<NativeProcess>
export declare function scipDecodeStart(filePath: string): ScipDecodeHandle
export declare class ScipDecodeHandle {
  metadata(): NapiScipMetadata
  nextDocument(): NapiScipDocument | null
  externalSymbols(): Array<NapiScipExternalSymbol>
}
